### ISSUE TITLE
Go dep vendored tests are failing

### ISSUE THREAD

**Issue by cedrickring** [cedrickring/golang-action#15]
For some reason after this commit, the tests are failing again:
https://github.com/cedrickring/golang-action/commit/f03f0f8b720ae8c7ae0f2dd49679adb48dbc0833

Run: https://github.com/cedrickring/golang-action/runs/79343982

@dougnukem some ideas?

**Comment by cedrickring** [comment]
I guess the problem is that the files, for some reason, are being shared between the action containers (?) and changes from other test checks are also reflected in `go dep vendored` check... 

Found out while messing around with the action in a docker container trying to reproduce that git difference. Otherwise I don't know how the `go_standard` folder could be modified...

**Comment by dougnukem** [comment]
@cedrickring that makes sense, i forgot it re-uses the same workspace. I'll make a fix for that.

**Comment by dougnukem** [comment]
@cedrickring there's a fix to `.gitignore` the built binary output which was causing `git status` to report workspace changes when its just a binary build that isn't meant to be part of the repo
