### ISSUE TITLE
go 1.13 entrypoint.sh not set as an executable

### ISSUE THREAD

**Issue by Aioxas** [cedrickring/golang-action#23]
I was having issues running cedrickring/golang-action/go1.13@1.4.0 in my workflow, and I think it has to do with entrypoint.sh not being set as an executable script but as a write/read file

**Comment by Aioxas** [comment]
I guess I could just have used cedrickring/golang-action@1.4.0 since that one properly sets up 1.13.

**Comment by cedrickring** [comment]
I guess I messed up while copying the files there 😅. I'll fix this now, so you can use `golang-action/go1.13` again.

**Comment by cedrickring** [comment]
`cedrickring/golang-action/go1.13:1.4.1` should work again :)
